lua/nvim-ts-autotag/internal.lua
For some people (like me) `vim.bo.filetype` returns  `'typescript.tsx'` and `'javascript.jsx'`, making `is_jsx` to return `false`.
This PR fixes the issues on typescript mentioned in #10.
=> including typescript.tsx and javascript.jsx filetypes

lua/nvim-ts-autotag/internal.lua
Now that treesitter supports markdown officially, it is possible to use autotag for HTML tags in Markdown with this PR.
=> feat: added markdown support

lua/nvim-ts-autotag/internal.lua
Make sure a parser is available before trying to rename tag.
Fixes #46
=> Check if there is a parser before renaming tag

README.md
Was noting the autotag was running in markdown but reading the README has no mention of this filetype. So adding this to clarify the defaults.
=> Update filetypes defaults in README

lua/nvim-ts-autotag/internal.lua
This PR enables support for html tags in htmldjango templates.
Fixes #48
=> Add htmldjango filetype

lua/nvim-ts-autotag/internal.lua
I received warning after upgrade nvim-treesitter.
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/6d0cee2f570ab848c0049be5a84a20acba3e8217/lua/nvim-treesitter/ts_utils.lua#L15) marked `ts_utils.get_node_text` as deprecated. In this PR, replace `ts_utils.get_node_text` with `vim.treesitter.query.get_node_text`
=> fix: ts_utils.get_node_text function deprecated

lua/nvim-ts-autotag/utils.lua
`vim.treesitter.query.get_node_text` is deprecated. Use `vim.treesitter.get_node_text` instead.
=> fix: `vim.treesitter.query.get_node_text` deprecated

lua/nvim-ts-autotag/internal.lua, sample/index.ts, tests/closetag_spec.lua
closes #32 
```js
const ex = html`<div`
//                  ^ cursor
```
Pressing `>` in insert mode produces:
```js
const ex = html`<div></div>`
//                   ^ cursor
```
then, <kbd>esc</kbd>`bciwp`<kbd>esc</kbd> produces:
```js
const ex = html`<p></p>`
```
also refactors attach function to use lua apis instead of vim.cmd
=> feat: js template tags

lua/nvim-ts-autotag/internal.lua, tests/close_slash_tag_spec.lua
Hello, I've been using Neovim exclusively for a while now.
One of the features I still miss in my Neovim is the ability, as in WebStorm, to automatically close an HTML tag when an opening tag is already available. (#94)
So, since I had some free time, I thought why not try to implement this feature myself and then share my modifications with you.
When you write code like this:
```html
<div>
hoi
<
```
And when you add a `/` at the after normally the start of a close tag, with this Pull Request the tag will automatically close with the correct name:
```html
<div>
hoi
</div>
```
Just a last small detail, since I'm not the most comfortable with treesitter and the source code of this repository, I tried to modify as little as possible to avoid stepping on the work that has already been done. …
=> feat: Add close tag after inputting /

lua/nvim-ts-autotag/internal.lua
resolves #152 
out of the main configuration
```lua
start_tag_pattern = { "tag_start" },
start_name_tag_pattern = { "element_identifier" },
end_tag_pattern = { "tag_end" },
end_name_tag_pattern = { "element_identifier" },
close_tag_pattern = { "erroneous_end_tag" },
close_name_tag_pattern = { "erroneous_end_tag_name" },
element_tag = { "element" },
skip_tag_pattern = { "quoted_attribute_value", "tag_end" },
```
i only encountered and correctly modified for my new type
```lua
start_tag_pattern
start_name_tag_pattern
end_tag_pattern
end_name_tag_pattern
```
The other variables i assumed from other elements, but i correctly now have in a simple templ file auto tag closing
https://github.com/windwp/nvim-ts-autotag/assets/2253299/c7d1b6d3-56a6-4da2-b1b7-8ee79164efd3
=> Templ tag completion

.github/workflows/ci.yml, lua/nvim-ts-autotag.lua, lua/nvim-ts-autotag/internal.lua, lua/nvim-ts-autotag/utils.lua, tests/minimal.vim
This PR removes the dependency on `nvim-treesitter` and uses Neovim's treesitter methods.
Without this PR, `nvim-ts-autotag` will be broken once the `nvim-treesitter` rewrite is released.
Some tests related to `eruby` seems to fail, but I'm not sure this is due to these code changes.
=> feat: remove dependency on `nvim-treesitter`. Needed for `nvim-treesitter` rewrite. Requires Neovim >= 0.9.4

lua/nvim-ts-autotag/config/ft.lua, lua/nvim-ts-autotag/internal.lua, lua/nvim-ts-autotag/utils.lua, tests/utils/helpers.lua, tests/utils/paths.lua, tests/utils/utils.lua
Partially resolves #174 
Closes #174
=> fix: use `0.9.5` compatible vim funcs

lua/nvim-ts-autotag/config/plugin.lua
This PR fixes the issue with auto renaming tags in Templ files.
Changes:
- Added patterns for start and end tags specific to Templ files.
- Updated skip patterns to handle Templ-specific nodes.
This ensures that tags in Templ files are correctly renamed automatically.
=> fix: auto renaming for Templ files

lua/nvim-ts-autotag/internal.lua, lua/nvim-ts-autotag/utils.lua
Fixes https://github.com/windwp/nvim-ts-autotag/issues/183
Tested manually on a local ruby erb file. Please let me know if you would like other tests added for this.
=> fix: wrap vim.treesitter.get_parser in pcall

lua/nvim-ts-autotag/config/plugin.lua
Previously I get the following warning when using the default config (by passing nothing):
`This function requires 1 argument(s) but instead it is receiving 0. Lua Diagnostics. (missing-parameter) [83, 8]`
The code itself works fine, it will use the default config.
This PR just updates the expected argument for `setup` to allow for `nil` as well
=> fix: update luadoc to allow for empty setup call

lua/nvim-ts-autotag/config/plugin.lua
Some frameworks like yew and leptos allow for html inside rust files, just updating implementation of [rayliwell](https://github.com/rayliwell) to add it to the og and keep just one plugin
=> Add rust file supports 

lua/nvim-ts-autotag.lua
I am currently using the `main` branch for nvim-treesitter which is the development branch for v1.0
https://github.com/nvim-treesitter/nvim-treesitter/issues/4767#issue-1698676665
> create a new `main` branch (targeting Neovim nightly only) for the new slimmed down installation functionality
This is causing nvim-ts-autotag to output an error, it tries to setup using the deprecated `configs` module, the main branch on TS has this removed. This error shows every time in the command line when opening Neovim.
The change on this PR fixes that error by inferring that we are using the main branch of TS. I tested this change on the latest version v0.9.2 of TS too, so it wont break current configs of users not using the main branch.
```
Failed to source `.../plugin/nvim-ts-autotag.lua` …
```
=> fix: error message when using nvim-treesitter 'main' branch

tests/minimal_init.lua
Copied from the body of the commit:
> - `popup.nvim` is not referenced anywhere within the plugin and as such
>   should be removed.
> - `playground` is not needed either, it's not referenced and secondly
>   the most important feature from it (:TSPlayground) is covered by
>   Neovim's :InspectTree command in more recent versions of Neovim.
>
> Closes #203 (https://github.com/windwp/nvim-ts-autotag/issues/203)
=> test(refactor): remove invalid test plugins

lua/nvim-ts-autotag/utils.lua, tests/specs/closetag_spec.lua
Use treesitter to determine whether node is a jsx_opening_element and use this info to bail out if the user may be writing a generic parameter.
Solves issue mentioned in https://github.com/windwp/nvim-ts-autotag/pull/202#issuecomment-2254467345 where `useState<>` becomes `useState<></>` when the user is typing out a generic type argument in `typescriptreact` files.
A thing to note is that there is still an ambiguity in the grammar while typing:
```tsx
// If the user types:
const foo = <T>
```
```tsx
// It could be a generic function:
const foo = <T>() => { ... };
```
```tsx
// Alternatively it could be a JSX element:
const foo = <T></T>;
```
But generic inline functions are less common than generic types and argument so this PR fixes most cases.
=> fix: Don't auto tag fragment if not in jsx

lua/nvim-ts-autotag/config/plugin.lua
Add support for HEEx files, including the `<.component></.component>` syntax.
HEEx is nearly the same as HTML except uses the `[start|end]_component` and `component_name` rather than `...tag...`.
Elixir templates are almost always HEEx, so I have also changed the Elixir alias from `html` -> `heex`.
I am already actively using this in my config :)
=> Add HEEx support including Components

lua/nvim-ts-autotag/internal.lua
close #222 
Avoid a potential infinite loop when checking if `is_in_template_tag()` when closing a `type_indentifier` ts node.
=> fix neovim freeze when closing a type_identifier
